FotoBlog/Models/ErrorViewModel.cs
namespace FotoBlog.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

FotoBlog/Models/YeniGonderiViewModel.cs
using FotoBlog.Attributes;
using System.ComponentModel.DataAnnotations;

namespace FotoBlog.Models
{
	public class YeniGonderiViewModel
	{
		[Display(Name = "Başlık")]
		[Required(ErrorMessage = "{0} girilmesi zorunludur")]
		public string Baslik { get; set; } = null!;


		[Display(Name = "Resim")]
		[Required(ErrorMessage = "{0} koyulması zorunludur.")]
		[GecerliResim(MaksimumDosyaBoyutuMb = 1.2)]
		public IFormFile Resim { get; set; } = null!;
	}
}

FotoBlog/Controllers/GonderilerController.cs
using FotoBlog.Data;
using FotoBlog.Models;
using Microsoft.AspNetCore.Mvc;

namespace FotoBlog.Controllers
{
	public class GonderilerController : Controller
	{
		private readonly UygulamaDbContext _db;
		private readonly IWebHostEnvironment _env;

		public GonderilerController(UygulamaDbContext db,IWebHostEnvironment env)
        {
			_db = db;
			_env = env;
		}
        public IActionResult Yeni()
		{
			return View();
		}

		[HttpPost, ValidateAntiForgeryToken]
		public IActionResult Yeni(YeniGonderiViewModel vm)
		{
			if (ModelState.IsValid)
			{
				string ext = Path.GetExtension(vm.Resim.FileName);
				string yeniDosyaAd = Guid.NewGuid() + ext;
				string yol = Path.Combine(_env.WebRootPath, "img","upload", yeniDosyaAd);

				using(var fs = new FileStream(yol, FileMode.CreateNew))
				{
					vm.Resim.CopyTo(fs);
				}
				var gonderi = new Gonderi();
				gonderi.Baslik = vm.Baslik;
				gonderi.ResimYolu = yeniDosyaAd;
				_db.Gonderiler.Add(gonderi);
				_db.SaveChanges();


				return RedirectToAction("Index", "Home", new { sonuc = "eklendi" });
			}

			return View();
		}
	}
}

FotoBlog/Controllers/HomeController.cs
using FotoBlog.Data;
using FotoBlog.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FotoBlog.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		private readonly UygulamaDbContext _db;

		public HomeController(ILogger<HomeController> logger,UygulamaDbContext db)
		{
			_logger = logger;
			_db = db;
		}

		public IActionResult Index()
		{
			return View(_db.Gonderiler
				.OrderByDescending(x=> x.Id)
				.ToList());
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

FotoBlog/Views/Gonderiler/Yeni.cshtml
@model YeniGonderiViewModel
@{
	ViewData["Title"] = "Yeni Gönderi";
}
<h2>@ViewBag.Title</h2>
<form asp-action="Yeni" enctype="multipart/form-data">
	<div class="mb-3">
		<label asp-for="Baslik" class="form-label"></label>
		<input asp-for="Baslik" type="text" class="form-control"/>
		<span asp-validation-for="Baslik" class="text-danger mt-1"></span>
	</div>
	<div class="mb-3">
		<label asp-for="Resim" class="form-label"></label>
		<input asp-for="Resim" type="file" class="form-control" />
		<span asp-validation-for="Resim" class="text-danger mt-1"></span>
	</div>
	<button type="submit" class="btn btn-primary">Ekle</button>
	<a class="btn btn-danger" asp-controller="Home" asp-action="Index">İptal</a>
</form>

FotoBlog/Views/Home/Index.cshtml
@model List<Gonderi>
@{
	ViewData["Title"] = "Home Page";
}


<div class="gonderiler">
	@if (Context.Request.Query["sonuc"] == "eklendi")
	{
		<div class="alert alert-success">
			Gönderi eklendi
		</div>
	}
	<div class="d-flex">
		<a asp-action="Yeni" asp-controller="Gonderiler" class="btn btn-success ms-auto mb-2">Yeni Gönderi Ekle</a>
	</div>
	@foreach (var item in Model)
	{
		<div class="mb-4">
			<h4>@item.Baslik</h4>
			<img class="w-100" src="~/img/upload/@item.ResimYolu" />
		</div>
	}
</div>

FotoBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FotoBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FotoBlog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FotoBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gonderiler" asp-action="Yeni">Gönderi Ekle</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FotoBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>